### ISSUE TITLE
Man page?

### ISSUE THREAD

**Issue by jayallen** [silentbicycle/ff#5]
Hi there.  Thanks for making this.  It's SOOOOOOOOOPER useful and has already become part of my typical workflow.

I was wondering it, perchance, you could include a proper man page in the future (even if it just contains the information in the README.  I install the utility via Homebrew on Mac OS X and I'm always surprised when I type 'man CMD' for a Homebrew installed utility and get an error.  That's especially true of the ones I use quite often.

Thanks much for your work!

**Comment by silentbicycle** [comment]
Thanks. :)

It probably should have one, agreed.

**Comment by silentbicycle** [comment]
Commit e8ffe57e241379b8958399d8a6f5a9bb87673670 adds a draft for a man page. Thoughts? I haven't written anything with {g,n,t}roff format before, so the file markup may be a bit off.

**Comment by silentbicycle** [comment]
After some style improvements, merged to master and tagged as 0.6 release (7f5f46271f4f77428c67f92f76c89adf18c72e0a), so brew can point at it.

**Comment by jayallen** [comment]
Beautiful!  Thanks so much for adding it and for the fantastic utility.
